### ISSUE TITLE
[BUG] First row of search tab

### ISSUE THREAD

**Issue by Dretra** [FaizanDurrani/Paperback-Public#70] opened 2020-04-24 13:44 UTC
**Describe the bug**
First row in serach result, you have to press icon of manga in the bottom part.
This only apllies to first row, other work fine

**To Reproduce**
Search for manga and try open in the upper part 

**Expected behaviour**
Whole icon working 

**App Version**
v0.3-b1

**Screenshots**
![image0 png](https://user-images.githubusercontent.com/64266695/80219249-7e1cc680-8642-11ea-9345-df9796ef54cc.jpg)

**Comment by FaizanDurrani** [comment] 2020-04-24 13:58
Duplicate of #67

**Closed by FaizanDurrani** 2020-04-24 13:58 UTC
Labels: bug

**Comment by Dretra** [comment] 2020-04-24 14:03
maybe in screenshot it looks like the are  shortened but on Ipad tkey look normal

**Comment by ZhongDev** [comment] 2020-04-25 02:46
@FaizanDurrani I believe this isn’t a duplicate of #67 because I think he means that the top part of the element does not respond to touch and only the bottom half does.
